//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Attendance_Manual_Log
    {
        public int Attendance_Manual_LogId { get; set; }
        public Nullable<long> EmpId { get; set; }
        public string EID { get; set; }
        public string ShiftCode { get; set; }
        public Nullable<System.TimeSpan> In_Time { get; set; }
        public Nullable<System.TimeSpan> Out_Time { get; set; }
        public Nullable<System.TimeSpan> Over_Time { get; set; }
        public Nullable<double> OT_Hour { get; set; }
        public Nullable<double> OT_Minute { get; set; }
        public Nullable<double> OT_Total { get; set; }
        public Nullable<bool> OT_Applicable { get; set; }
        public string AttendanceStatus { get; set; }
        public string AttendanceRemarks { get; set; }
        public Nullable<System.DateTime> Attendance_Date { get; set; }
        public string Attendance_Day { get; set; }
        public string Working_DayType { get; set; }
        public Nullable<int> Update_Status { get; set; }
        public Nullable<bool> Attendance_Process_Status { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string Ip_Address { get; set; }
    }
}
