//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_AdvanceSalaryDetailPrevious_Log
    {
        public int AdvanceSalaryDetailsLogId { get; set; }
        public Nullable<long> AdvanceSalaryDetailsId { get; set; }
        public string ASCode { get; set; }
        public string EID { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<int> ResionId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<decimal> InstalmentAmount { get; set; }
        public Nullable<int> NoOfInstalment { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.Guid> EDIT_USER { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
        public string OCODE { get; set; }
        public Nullable<bool> AdvanceDeduction { get; set; }
        public string Remarks { get; set; }
    }
}
