//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_AdvanceSalarySummary
    {
        public long AdvanceSalaryId { get; set; }
        public string AdvancePay_Code { get; set; }
        public string EID { get; set; }
        public Nullable<decimal> TotalAdvance_Amount { get; set; }
        public Nullable<decimal> Advance_Installment_Amount { get; set; }
        public Nullable<int> Number_Of_Installment { get; set; }
        public Nullable<System.DateTime> Advance_FromDate { get; set; }
        public Nullable<System.DateTime> Advance_ToDate { get; set; }
        public Nullable<System.DateTime> PayScheduleDate { get; set; }
        public Nullable<decimal> ReceiveAmount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public string AdvanceRemarks { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
