//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_LeaveApply
    {
        public int LeaveId { get; set; }
        public string LeaveCode { get; set; }
        public string EID { get; set; }
        public string LeaveTypeCode { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<System.DateTime> LeaveDateFrom { get; set; }
        public Nullable<System.DateTime> LeaveDateTo { get; set; }
        public Nullable<int> TotalLeave { get; set; }
        public string SupervisorEID { get; set; }
        public Nullable<bool> SupervisorApproveStatus { get; set; }
        public Nullable<System.DateTime> SupervisorApproveDate { get; set; }
        public string Remarks { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string EditBy { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
