//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Salary_Deduction
    {
        public int Salary_Deduction_Id { get; set; }
        public string EID { get; set; }
        public string Salary_DeductType { get; set; }
        public Nullable<double> Salary_DeductDay { get; set; }
        public Nullable<decimal> Salary_Deduct_Amount { get; set; }
        public Nullable<System.DateTime> Salary_DeductDate { get; set; }
        public string ApprovedBy { get; set; }
        public string Remark { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
