//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MedicinUnit
    {
        public tbl_MedicinUnit()
        {
            this.tbl_IndorBloodSalesDetails = new HashSet<tbl_IndorBloodSalesDetails>();
            this.tbl_MedicineInfo = new HashSet<tbl_MedicineInfo>();
            this.tbl_OutdorBloodSalesDetails = new HashSet<tbl_OutdorBloodSalesDetails>();
        }
    
        public int MediUnitID { get; set; }
        public string UnitName { get; set; }
    
        public virtual ICollection<tbl_IndorBloodSalesDetails> tbl_IndorBloodSalesDetails { get; set; }
        public virtual ICollection<tbl_MedicineInfo> tbl_MedicineInfo { get; set; }
        public virtual ICollection<tbl_OutdorBloodSalesDetails> tbl_OutdorBloodSalesDetails { get; set; }
    }
}
