//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Loan
    {
        public int LoanID { get; set; }
        public int StaffID { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
        public string LoanPurpose { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<decimal> NewLoan { get; set; }
        public Nullable<decimal> LoanBack { get; set; }
        public string PaymentWay { get; set; }
        public Nullable<decimal> GrandTotalLoan { get; set; }
        public Nullable<int> PaidLoan { get; set; }
        public string Remarks { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual tbl_staffInfo tbl_staffInfo { get; set; }
        public virtual tbl_UserInfo tbl_UserInfo { get; set; }
    }
}
