//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MedicinCatagory
    {
        public tbl_MedicinCatagory()
        {
            this.tbl_MedicineInfo = new HashSet<tbl_MedicineInfo>();
        }
    
        public int MediCataID { get; set; }
        public string CatagoryName { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<tbl_MedicineInfo> tbl_MedicineInfo { get; set; }
    }
}
