//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Service
    {
        public tbl_Service()
        {
            this.tbl_InvoiceDetails = new HashSet<tbl_InvoiceDetails>();
        }
    
        public int ServiceId { get; set; }
        public string ServiceName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tbl_InvoiceDetails> tbl_InvoiceDetails { get; set; }
    }
}
