//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BloodSupplierInfo
    {
        public tbl_BloodSupplierInfo()
        {
            this.tbl_BloodPurchaseVoucher = new HashSet<tbl_BloodPurchaseVoucher>();
            this.tbl_BloodSupplierProfile = new HashSet<tbl_BloodSupplierProfile>();
        }
    
        public int BloodSupplyerID { get; set; }
        public string CompanyName { get; set; }
        public string ComAddress { get; set; }
        public string ComMobNo { get; set; }
        public string ContactPerson { get; set; }
        public string ContractPersMobNo { get; set; }
        public string Email { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<tbl_BloodPurchaseVoucher> tbl_BloodPurchaseVoucher { get; set; }
        public virtual ICollection<tbl_BloodSupplierProfile> tbl_BloodSupplierProfile { get; set; }
    }
}
