//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Referenceinfo
    {
        public tbl_Referenceinfo()
        {
            this.tbl_PatientInfo = new HashSet<tbl_PatientInfo>();
        }
    
        public int ReferenceID { get; set; }
        public string ReferenceName { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string AgreementInfo { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> TimeDuration { get; set; }
    
        public virtual ICollection<tbl_PatientInfo> tbl_PatientInfo { get; set; }
    }
}
