//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StaffEducation
    {
        public int StaffEducaID { get; set; }
        public string StaffEducaName { get; set; }
        public int StaffID { get; set; }
        public string Organization { get; set; }
        public string Remarks { get; set; }
    
        public virtual tbl_staffInfo tbl_staffInfo { get; set; }
    }
}
