//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DesignationType
    {
        public tbl_DesignationType()
        {
            this.tbl_staffInfo = new HashSet<tbl_staffInfo>();
        }
    
        public int DesignationID { get; set; }
        public string DesingnationName { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<tbl_staffInfo> tbl_staffInfo { get; set; }
    }
}
