//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OutdorMedicineSalesVoucher
    {
        public tbl_OutdorMedicineSalesVoucher()
        {
            this.tbl_OutdorMedicineSalesDetails = new HashSet<tbl_OutdorMedicineSalesDetails>();
        }
    
        public string OutdorMedicineSalesVoucherNo { get; set; }
        public string OutdorPatientName { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> GrandTotalAmount { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public int UserInfoID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Address { get; set; }
        public string MobNo { get; set; }
    
        public virtual ICollection<tbl_OutdorMedicineSalesDetails> tbl_OutdorMedicineSalesDetails { get; set; }
        public virtual tbl_UserInfo tbl_UserInfo { get; set; }
    }
}
