//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AmbulanceSchedule
    {
        public int AmbSchedulID { get; set; }
        public int AmbID { get; set; }
        public string TargetLocation { get; set; }
        public string GoingTime { get; set; }
        public string BackTime { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PatientDescription { get; set; }
        public string FreeOrBusy { get; set; }
        public string Remarks { get; set; }
    
        public virtual tbl_AmbulanceInfo tbl_AmbulanceInfo { get; set; }
    }
}
