//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DoctorSpecialization
    {
        public int DoctorSpecialiID { get; set; }
        public int StaffID { get; set; }
        public int SpeciaTypeID { get; set; }
        public string Remarks { get; set; }
    
        public virtual tbl_SpecializationType tbl_SpecializationType { get; set; }
        public virtual tbl_staffInfo tbl_staffInfo { get; set; }
    }
}
