//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AmbulanceInfo
    {
        public tbl_AmbulanceInfo()
        {
            this.tbl_AmbulanceSchedule = new HashSet<tbl_AmbulanceSchedule>();
        }
    
        public int AmbID { get; set; }
        public string AmbPlateNo { get; set; }
        public int AmbCatagoryID { get; set; }
        public int StaffID { get; set; }
        public string FreeOrBusy { get; set; }
    
        public virtual tbl_AmbCatagory tbl_AmbCatagory { get; set; }
        public virtual tbl_staffInfo tbl_staffInfo { get; set; }
        public virtual ICollection<tbl_AmbulanceSchedule> tbl_AmbulanceSchedule { get; set; }
    }
}
