//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BloodDonerInfo
    {
        public int BloodDonerID { get; set; }
        public string BloodDonerName { get; set; }
        public string Age { get; set; }
        public string Weight { get; set; }
        public string Address { get; set; }
        public int BloodID { get; set; }
        public string MobNo { get; set; }
        public string BloodDonerEmail { get; set; }
        public Nullable<decimal> BloodAmount { get; set; }
        public string NationalId { get; set; }
        public string Remarks { get; set; }
    
        public virtual tbl_BloodGroup tbl_BloodGroup { get; set; }
    }
}
