//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InvoiceVocher
    {
        public tbl_InvoiceVocher()
        {
            this.tbl_InvoiceDetails = new HashSet<tbl_InvoiceDetails>();
        }
    
        public string InvoiceVoucherNo { get; set; }
        public int PatientID { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> GrandTotalAmount { get; set; }
        public string Remarks { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<tbl_InvoiceDetails> tbl_InvoiceDetails { get; set; }
        public virtual tbl_PatientInfo tbl_PatientInfo { get; set; }
        public virtual tbl_UserInfo tbl_UserInfo { get; set; }
    }
}
