//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RoomType
    {
        public tbl_RoomType()
        {
            this.tbl_PationRoomInformation = new HashSet<tbl_PationRoomInformation>();
        }
    
        public int RoomTypeID { get; set; }
        public string RoomTypeName { get; set; }
    
        public virtual ICollection<tbl_PationRoomInformation> tbl_PationRoomInformation { get; set; }
    }
}
