//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OutdorBloodSalesVoucher
    {
        public tbl_OutdorBloodSalesVoucher()
        {
            this.tbl_OutdorBloodSalesDetails = new HashSet<tbl_OutdorBloodSalesDetails>();
        }
    
        public string OutdorBloodSalesVoucherNo { get; set; }
        public string OutdorBuyerName { get; set; }
        public string OutdorBuyerPnoneNo { get; set; }
        public string OutdorBuyerAddress { get; set; }
        public Nullable<decimal> GrandTotalAmount { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<decimal> DeuAmount { get; set; }
        public string Remarks { get; set; }
        public int UserInfoID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<tbl_OutdorBloodSalesDetails> tbl_OutdorBloodSalesDetails { get; set; }
        public virtual tbl_UserInfo tbl_UserInfo { get; set; }
    }
}
