//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BloodPurchaseVoucher
    {
        public tbl_BloodPurchaseVoucher()
        {
            this.tbl_BloodPurchaseeDetails = new HashSet<tbl_BloodPurchaseeDetails>();
        }
    
        public string BloodPurchaseVoucherNo { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public int BloodSupplyerID { get; set; }
        public Nullable<decimal> GrandTotalAmount { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public string Remark { get; set; }
        public int UserInfoID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<tbl_BloodPurchaseeDetails> tbl_BloodPurchaseeDetails { get; set; }
        public virtual tbl_BloodSupplierInfo tbl_BloodSupplierInfo { get; set; }
        public virtual tbl_UserInfo tbl_UserInfo { get; set; }
    }
}
