//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LabInfo
    {
        public tbl_LabInfo()
        {
            this.Tbl_IndorPatientLabTest = new HashSet<Tbl_IndorPatientLabTest>();
            this.tbl_OutdorPatientLabTest = new HashSet<tbl_OutdorPatientLabTest>();
        }
    
        public int LabID { get; set; }
        public string Shift { get; set; }
        public string LabNo { get; set; }
        public string LabName { get; set; }
        public int StaffID { get; set; }
        public string LabDescription { get; set; }
    
        public virtual ICollection<Tbl_IndorPatientLabTest> Tbl_IndorPatientLabTest { get; set; }
        public virtual tbl_staffInfo tbl_staffInfo { get; set; }
        public virtual ICollection<tbl_OutdorPatientLabTest> tbl_OutdorPatientLabTest { get; set; }
    }
}
