//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserInfo
    {
        public tbl_UserInfo()
        {
            this.tbl_Advance = new HashSet<tbl_Advance>();
            this.tbl_AppointmentSchedule = new HashSet<tbl_AppointmentSchedule>();
            this.tbl_Attendance = new HashSet<tbl_Attendance>();
            this.tbl_BloodPurchaseVoucher = new HashSet<tbl_BloodPurchaseVoucher>();
            this.tbl_BloodSupplierProfile = new HashSet<tbl_BloodSupplierProfile>();
            this.tbl_IndorBloodSalesVoucher = new HashSet<tbl_IndorBloodSalesVoucher>();
            this.tbl_IndorMedicenPurshaseVoucher = new HashSet<tbl_IndorMedicenPurshaseVoucher>();
            this.tbl_IndorMedicineSalesVoucher = new HashSet<tbl_IndorMedicineSalesVoucher>();
            this.Tbl_IndorPatientLabTest = new HashSet<Tbl_IndorPatientLabTest>();
            this.tbl_InvoiceVocher = new HashSet<tbl_InvoiceVocher>();
            this.tbl_Leave = new HashSet<tbl_Leave>();
            this.tbl_Loan = new HashSet<tbl_Loan>();
            this.tbl_MedicineSupplierProfile = new HashSet<tbl_MedicineSupplierProfile>();
            this.tbl_OutdorBloodSalesVoucher = new HashSet<tbl_OutdorBloodSalesVoucher>();
            this.tbl_OutdorMedicineSalesVoucher = new HashSet<tbl_OutdorMedicineSalesVoucher>();
            this.tbl_OutdorPatientLabTest = new HashSet<tbl_OutdorPatientLabTest>();
            this.tbl_Salary = new HashSet<tbl_Salary>();
        }
    
        public int UserInfoID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int StaffID { get; set; }
        public int UserRoleID { get; set; }
        public string Isactive { get; set; }
        public string Remars { get; set; }
    
        public virtual ICollection<tbl_Advance> tbl_Advance { get; set; }
        public virtual ICollection<tbl_AppointmentSchedule> tbl_AppointmentSchedule { get; set; }
        public virtual ICollection<tbl_Attendance> tbl_Attendance { get; set; }
        public virtual ICollection<tbl_BloodPurchaseVoucher> tbl_BloodPurchaseVoucher { get; set; }
        public virtual ICollection<tbl_BloodSupplierProfile> tbl_BloodSupplierProfile { get; set; }
        public virtual ICollection<tbl_IndorBloodSalesVoucher> tbl_IndorBloodSalesVoucher { get; set; }
        public virtual ICollection<tbl_IndorMedicenPurshaseVoucher> tbl_IndorMedicenPurshaseVoucher { get; set; }
        public virtual ICollection<tbl_IndorMedicineSalesVoucher> tbl_IndorMedicineSalesVoucher { get; set; }
        public virtual ICollection<Tbl_IndorPatientLabTest> Tbl_IndorPatientLabTest { get; set; }
        public virtual ICollection<tbl_InvoiceVocher> tbl_InvoiceVocher { get; set; }
        public virtual ICollection<tbl_Leave> tbl_Leave { get; set; }
        public virtual ICollection<tbl_Loan> tbl_Loan { get; set; }
        public virtual ICollection<tbl_MedicineSupplierProfile> tbl_MedicineSupplierProfile { get; set; }
        public virtual ICollection<tbl_OutdorBloodSalesVoucher> tbl_OutdorBloodSalesVoucher { get; set; }
        public virtual ICollection<tbl_OutdorMedicineSalesVoucher> tbl_OutdorMedicineSalesVoucher { get; set; }
        public virtual ICollection<tbl_OutdorPatientLabTest> tbl_OutdorPatientLabTest { get; set; }
        public virtual ICollection<tbl_Salary> tbl_Salary { get; set; }
        public virtual tbl_staffInfo tbl_staffInfo { get; set; }
        public virtual tbl_UserRole tbl_UserRole { get; set; }
    }
}
