//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AllowanceType
    {
        public tbl_AllowanceType()
        {
            this.tbl_AllowanceDetails = new HashSet<tbl_AllowanceDetails>();
        }
    
        public int AllowanceID { get; set; }
        public string AllowanceName { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<tbl_AllowanceDetails> tbl_AllowanceDetails { get; set; }
    }
}
