//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_IndorBloodSalesVoucher
    {
        public tbl_IndorBloodSalesVoucher()
        {
            this.tbl_IndorBloodSalesDetails = new HashSet<tbl_IndorBloodSalesDetails>();
        }
    
        public string IndorBloodsalesVoucherNo { get; set; }
        public string BuyerName { get; set; }
        public string BuyerAddress { get; set; }
        public Nullable<decimal> GrandTotalAmount { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<decimal> DeuAmount { get; set; }
        public string Remarks { get; set; }
        public int UserInfoID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<tbl_IndorBloodSalesDetails> tbl_IndorBloodSalesDetails { get; set; }
        public virtual tbl_UserInfo tbl_UserInfo { get; set; }
    }
}
