//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OperationInfo
    {
        public int OperationID { get; set; }
        public string OperationName { get; set; }
        public Nullable<int> PatientID { get; set; }
        public int StaffID { get; set; }
        public int DoctorID { get; set; }
        public int NurseID { get; set; }
        public string RoomNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remarks { get; set; }
    
        public virtual tbl_staffInfo tbl_staffInfo { get; set; }
    }
}
