//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BloodPurchaseeDetails
    {
        public int BloodPurchaseID { get; set; }
        public string BloodPurchaseVoucherNo { get; set; }
        public int BloodID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual tbl_BloodGroup tbl_BloodGroup { get; set; }
        public virtual tbl_BloodPurchaseVoucher tbl_BloodPurchaseVoucher { get; set; }
    }
}
