//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Salary
    {
        public int SalaryID { get; set; }
        public int StaffID { get; set; }
        public Nullable<decimal> BasicAmount { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> AllowanceAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> DetuctionAmount { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public Nullable<decimal> AdvanceBack { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<decimal> LoanBack { get; set; }
        public Nullable<decimal> GrandTotalAmount { get; set; }
        public string Remarks { get; set; }
        public int UserInfoID { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual tbl_staffInfo tbl_staffInfo { get; set; }
        public virtual tbl_UserInfo tbl_UserInfo { get; set; }
    }
}
