//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PationRoomInformation
    {
        public tbl_PationRoomInformation()
        {
            this.tbl_PatientInfo = new HashSet<tbl_PatientInfo>();
        }
    
        public int PRoomID { get; set; }
        public string ProomNo { get; set; }
        public int CategorayID { get; set; }
        public int RoomTypeID { get; set; }
        public string FloorNo { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual ICollection<tbl_PatientInfo> tbl_PatientInfo { get; set; }
        public virtual tbl_RoomCatagory tbl_RoomCatagory { get; set; }
        public virtual tbl_RoomType tbl_RoomType { get; set; }
    }
}
