//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MedicineSupplierInfo
    {
        public tbl_MedicineSupplierInfo()
        {
            this.tbl_IndorMedicenPurshaseVoucher = new HashSet<tbl_IndorMedicenPurshaseVoucher>();
            this.tbl_MedicineSupplierProfile = new HashSet<tbl_MedicineSupplierProfile>();
        }
    
        public int MediSupplyerID { get; set; }
        public string MediSupplyerName { get; set; }
        public string ComAddress { get; set; }
        public string ComMobNo { get; set; }
        public string ContractPerson { get; set; }
        public string ContractPersMobNo { get; set; }
        public string Email { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<tbl_IndorMedicenPurshaseVoucher> tbl_IndorMedicenPurshaseVoucher { get; set; }
        public virtual ICollection<tbl_MedicineSupplierProfile> tbl_MedicineSupplierProfile { get; set; }
    }
}
