//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AllowanceVoucher
    {
        public tbl_AllowanceVoucher()
        {
            this.tbl_AllowanceDetails = new HashSet<tbl_AllowanceDetails>();
        }
    
        public string AllowanceVocherNo { get; set; }
        public int StaffID { get; set; }
        public Nullable<decimal> GrandTotalAmount { get; set; }
    
        public virtual ICollection<tbl_AllowanceDetails> tbl_AllowanceDetails { get; set; }
        public virtual tbl_staffInfo tbl_staffInfo { get; set; }
    }
}
