//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_staffInfo
    {
        public tbl_staffInfo()
        {
            this.tbl_Advance = new HashSet<tbl_Advance>();
            this.tbl_AllowanceVoucher = new HashSet<tbl_AllowanceVoucher>();
            this.tbl_AmbulanceInfo = new HashSet<tbl_AmbulanceInfo>();
            this.tbl_AppointmentSchedule = new HashSet<tbl_AppointmentSchedule>();
            this.tbl_Attendance = new HashSet<tbl_Attendance>();
            this.tbl_DoctorDuty = new HashSet<tbl_DoctorDuty>();
            this.tbl_DoctorSpecialization = new HashSet<tbl_DoctorSpecialization>();
            this.tbl_LabInfo = new HashSet<tbl_LabInfo>();
            this.tbl_Leave = new HashSet<tbl_Leave>();
            this.tbl_Loan = new HashSet<tbl_Loan>();
            this.tbl_NurseDuty = new HashSet<tbl_NurseDuty>();
            this.tbl_OperationInfo = new HashSet<tbl_OperationInfo>();
            this.tbl_Salary = new HashSet<tbl_Salary>();
            this.tbl_StaffEducation = new HashSet<tbl_StaffEducation>();
            this.tbl_UserInfo = new HashSet<tbl_UserInfo>();
        }
    
        public int StaffID { get; set; }
        public string Name { get; set; }
        public int StaffTypeID { get; set; }
        public int DesignationID { get; set; }
        public string PresentAddress { get; set; }
        public string ParmanentAddress { get; set; }
        public string MobNo { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> ConfermationDate { get; set; }
        public Nullable<System.DateTime> ReginingDate { get; set; }
        public string EmailNo { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<tbl_Advance> tbl_Advance { get; set; }
        public virtual ICollection<tbl_AllowanceVoucher> tbl_AllowanceVoucher { get; set; }
        public virtual ICollection<tbl_AmbulanceInfo> tbl_AmbulanceInfo { get; set; }
        public virtual ICollection<tbl_AppointmentSchedule> tbl_AppointmentSchedule { get; set; }
        public virtual ICollection<tbl_Attendance> tbl_Attendance { get; set; }
        public virtual tbl_DesignationType tbl_DesignationType { get; set; }
        public virtual ICollection<tbl_DoctorDuty> tbl_DoctorDuty { get; set; }
        public virtual ICollection<tbl_DoctorSpecialization> tbl_DoctorSpecialization { get; set; }
        public virtual ICollection<tbl_LabInfo> tbl_LabInfo { get; set; }
        public virtual ICollection<tbl_Leave> tbl_Leave { get; set; }
        public virtual ICollection<tbl_Loan> tbl_Loan { get; set; }
        public virtual ICollection<tbl_NurseDuty> tbl_NurseDuty { get; set; }
        public virtual ICollection<tbl_OperationInfo> tbl_OperationInfo { get; set; }
        public virtual ICollection<tbl_Salary> tbl_Salary { get; set; }
        public virtual ICollection<tbl_StaffEducation> tbl_StaffEducation { get; set; }
        public virtual tbl_StaffType tbl_StaffType { get; set; }
        public virtual ICollection<tbl_UserInfo> tbl_UserInfo { get; set; }
    }
}
