//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Advance
    {
        public int AdvanceID { get; set; }
        public int StaffID { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<System.DateTime> AdvanceDate { get; set; }
        public string AdvancePurpose { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public Nullable<decimal> NewAdvance { get; set; }
        public Nullable<decimal> AdvanceBack { get; set; }
        public string PaymentWay { get; set; }
        public Nullable<decimal> GrandTotalAmount { get; set; }
        public Nullable<int> Paid { get; set; }
        public string Remarks { get; set; }
        public int UserInfoID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual tbl_staffInfo tbl_staffInfo { get; set; }
        public virtual tbl_UserInfo tbl_UserInfo { get; set; }
    }
}
