//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PatientInfo
    {
        public tbl_PatientInfo()
        {
            this.tbl_IndorMedicineSalesVoucher = new HashSet<tbl_IndorMedicineSalesVoucher>();
            this.Tbl_IndorPatientLabTest = new HashSet<Tbl_IndorPatientLabTest>();
            this.tbl_InvoiceVocher = new HashSet<tbl_InvoiceVocher>();
        }
    
        public int PatientID { get; set; }
        public string PatientName { get; set; }
        public string Age { get; set; }
        public string Weight { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string PatientMobNo { get; set; }
        public string Disease { get; set; }
        public int ReferenceID { get; set; }
        public string Gardian { get; set; }
        public string EmergencyMobNo { get; set; }
        public int PRoomID { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<tbl_IndorMedicineSalesVoucher> tbl_IndorMedicineSalesVoucher { get; set; }
        public virtual ICollection<Tbl_IndorPatientLabTest> Tbl_IndorPatientLabTest { get; set; }
        public virtual ICollection<tbl_InvoiceVocher> tbl_InvoiceVocher { get; set; }
        public virtual tbl_PationRoomInformation tbl_PationRoomInformation { get; set; }
        public virtual tbl_Referenceinfo tbl_Referenceinfo { get; set; }
    }
}
