//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OutdorMedicineSalesDetails
    {
        public int OutdorMedicenSaleseId { get; set; }
        public string OutdorMedicineSalesVoucherNo { get; set; }
        public int MediInfoID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual tbl_MedicineInfo tbl_MedicineInfo { get; set; }
        public virtual tbl_MedicineInfo tbl_MedicineInfo1 { get; set; }
        public virtual tbl_OutdorMedicineSalesVoucher tbl_OutdorMedicineSalesVoucher { get; set; }
    }
}
